<?php

namespace ProtoMapper\Config;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-01 at 03:11:37.
 */
class ConfigLoaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ConfigLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        //BEGIN: test loading using the configuration file in "/examples/protocol.config.xml"
        $this->object = new ConfigLoader();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers ProtoMapper\Config\ConfigLoader::testParseProtocols
     * @todo   Implement testParse().
     */
    public function testParse() {
        $this->object->load('..//examples//protocol.config.xml');
        $definition = $this->object->getProtocolDefinition("LinkedIn", "Data");
        //TODO: validate contents
    }
}
